services:
    nginx:
      image: nginx:alpine
      container_name: ${NAME_CONTAINER}_nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 98:80
      depends_on:
          - php-fpm
          - mysql
    php-fpm:
      build: ./docker/php-fpm
      container_name: ${NAME_CONTAINER}_php
      working_dir: /application
      environment: 
        XDEBUG_MODE: coverage
      volumes:
        - .:/application
      networks:
        - default
    mysql:
      image: mysql:5.7
      container_name: ${NAME_CONTAINER}_mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
        - "3306:8989"
      volumes:
        - ./docker/.data/db:/var/lib/mysql
      networks:
        - default
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
        - mysql
      ports:
        - 88:80
      environment:
        - PMA_ARBITRARY=1    
